name: Events Demo
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Manual trigger
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event
        run: echo "Triggered by ${{ github.event_name }}"
