# devsecops-pipeline.yml - Fetch live scores and deploy statically with GitHub Actions
name: DevSecOps Pipeline
on:
  push:
    branches: [main]
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes
  workflow_dispatch:
permissions:
  contents: write # Grant write access to the repository
  pages: write # Grant write access to GitHub Pages
  id-token: write # For future-proofing
  issues: write # Grant permission to create issues (for ZAP integration)
jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - run: echo "Fetching live scores"
      - name: Fetch Live Scores
        run: node index.js
        env:
          CRICAPI_KEY: ${{ secrets.CRICAPI_KEY }}
      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: './'
          exclude: 'node_modules'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Notify Slack
        if: env.SLACK_WEBHOOK_URL != null # Skip if not set
        uses: slackapi/slack-github-action@v1.24.0
        with:
          slack-message: 'Cricket Scoring App scores updated successfully!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Log Slack Skip
        if: env.SLACK_WEBHOOK_URL == null
        run: echo "Slack notification skipped because SLACK_WEBHOOK_URL is not configured."

  post-deploy:
    runs-on: ubuntu-latest
    needs: fetch-and-deploy
    steps:
      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://nandurilaxman.github.io/congenial-meme/' # Updated to the correct URL
          report_json: report_json.json
          report_md: report_md.md
          report_html: report_html.html
          fail_on_warning: false # Prevents failure on warnings
