name: Secrets Demo
on: [push]
jobs:
  secrets-demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Secret is ${{ secrets.MY_SECRET }}"
      - run: echo "Env var is $MY_ENV_VAR"
        env:
          MY_ENV_VAR: "Hello from env"
